### ISSUE TITLE
Error in installing flipPlots

### ISSUE THREAD

**Issue by abuegho** [Displayr/flipPlots#2]
When running `install_github("Displayr/flipPlots")`, I get:
`Error in utils::download.file(url, path, method = download_method(), quiet = quiet, : cannot open URL`

even when I try to install it manually
`install.packages("~/Desktop/Displayr-flipPlots-544724a.tar.gz", repos = NULL, type = "source")`
I get this:
```
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: dependency 'flipTransformations' is not available for package 'flipPlots'
* removing '~/R/R-3.6.0/library/flipPlots'
Warning in install.packages :
  installation of package ‘~/Desktop/Displayr-flipPlots-544724a.tar.gz’ had non-zero exit status
```
I would really appreciate any help in the matter.
Thanks,

**Comment by chschan** [comment]
I wasn't able to recreate your error. I would have expected install_github to automatically install flipTransformations for you. If you run
`devtools::install_github("Displayr/flipTransformations")`
do you get an error message?

**Comment by abuegho** [comment]
When I run `devtools::install_github("Displayr/flipPlots")` I also get:
 `Downloading GitHub repo Displayr/flipPlots@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/Displayr/flipPlots/tarball/master'`

**Comment by chschan** [comment]
Try installing flipTransformations instead of flipPlots. I'm just wondering if its a problem with this package or the permissions on it, or a different issue.

The error message sounds like this: https://github.com/r-lib/remotes/issues/130. Have you tried updating your version of remotes and devtools?

**Comment by abuegho** [comment]
I'm getting the same error when I try to get flipTransformation. my packages are all up to date, and I'm running the latest version of R & RStudio.

**Comment by mwmclean** [comment]
This does not seem like an issue with `flipPlots` and instead an issue with installing packages on your machine. What packages/repositories are you actually able to install with `remotes::install_github()` from other organizations/users? I suggest you see [this issue](https://github.com/r-lib/remotes/issues/130) in `remotes` and specifically [this comment](https://github.com/r-lib/remotes/issues/130#issuecomment-423830669).
