### ISSUE TITLE
How to save as image instead of html widget?

### ISSUE THREAD

**Issue by jzadra** [Displayr/flipPlots#4]
Is there a way to save output to an image?

**Comment by chschan** [comment]
You can try this (but it isn't guaranteed to work for all widgets). 
* convert widget to html using `htmlwidgets::saveWidget(widget, <out.html>)`
* install webshot from CRAN
* run `webshot::install_phantomjs()`. Check the docs for platform-specific info
* run `webshot::webshot(<out.html>, file = <out.png>)`. There  are strange things about this functions path handling so the html files might need to be in the current directory when you run this
