### ISSUE TITLE
Typo in sankeydiagram.R line 429 

### ISSUE THREAD

**Issue by thelautiff** [Displayr/flipPlots#7]
Hi! I think there's a typo in line 429 - it should be

x.fac <- factor(x)

and not

x.fac <- Factor(x)

Had to copy-paste the whole code chunk since my workplace has banned installing packages straight from github so not sure if it has anything to do with that. The code got stuck and when I ran it with the debugger it brought up this line. Changing it to lowercase f fixed my problem.

Great package by the way - thanks!

**Comment by mwmclean** [comment]
No, this is not a typo. `Factor` (with a capital 'F') is a function we import from another package we maintain, `flipTransformations`, which offers some additional functionality to `base::factor`.

**Comment by thelautiff** [comment]
I see- thanks for clarifying! Yea I skimped on copy-pasting all the code in since i had to do it manually...
