### ISSUE TITLE
Problem to install this package

### ISSUE THREAD

**Issue by darwinalexander** [Displayr/flipPlots#8]
I have these errors:

> remotes::install_github("Displayr/flipPlots")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 164.163.135.109. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-05-02 06:14:15 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
  - 
#################################

> install_github("Displayr/flipPlots")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 164.163.135.109. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-05-02 06:14:16 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

**Comment by jrwishart** [comment]
This error is a restriction made by github on the number of requests to their servers. The solution is to do the steps mentioned in the error message. Have you

1. Made a github PAT (personal access token)?  see `usethis::browse_github_pat()` or create one in github via https://github.com/settings/tokens
2. Once you have a PAT, have you added it to your R Environment?  see `usethis::edit_r_environ()` and add your PAT by adding a line `GITHUB_PAT=xxxxxxxxxxxx` (where xxxxxxx is your generated PAT)

If not, please do those steps.

**Comment by iiiir** [comment]
I got another error after done the steps:
...
ERROR: this R is version 3.6.1, package 'verbs' requires R >= 4.0.0

I managed to by pass the error by installing an older commit of verbs (randomly picked by date...):
> install_github("Displayr/verbs@b6386bc")

Then worked.

**Comment by jrwishart** [comment]
Alternatively, install R 4.0.0 or a higher version as the error message suggests.
